version: '3'
services:
  backend:
    image: back
    ports:
      - '8000:8000'
    environment:
      - 'FRONT_URL=http://localhost:5000'

  frontend:
    image: front
    ports:
      - '5000:5000'
    environment:
      - 'API_URL=http://localhost:8000'
