FROM ubuntu:16.04

WORKDIR /myapp
COPY . .

RUN apt-get update && apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs

RUN node -v && npm -v

RUN npm install
RUN npm install -g serve

ENV API_URL=http://localhost:8000

EXPOSE 5000

ENTRYPOINT npm start